Sylius\Component\Core\Model\Order:
    properties:
        shippingAddress: ~
        billingAddress: ~
        payments: ~
        currencyCode:
            faker: currencyCode
            prefix: 'anonymized-'
        localeCode:
            faker: locale
        customerIp:
            value: null
        notes:
            faker: text
