synolia_sylius_gdpr_admin_anonymize_customer:
    path: /customers/{id}/anonymize
    methods: POST|GET
    controller: Synolia\SyliusGDPRPlugin\Controller\AnonymizationController

synolia_sylius_gdpr_admin_export_customer_datas:
    path: /customers/{id}/export-data
    methods: POST|GET
    controller: Synolia\SyliusGDPRPlugin\Controller\ExportDataController
