Sylius\Component\Core\Model\Adjusment:
    attributes:
        label: &defaultGroup
            groups:
                - !php/const Synolia\SyliusGDPRPlugin\Enum\GDPRSerializationKeyEnum::CUSTOMER_DATA
        amount: *defaultGroup
